name: Kramer, What's Going On In There?
source: https://knowyourmeme.com/memes/kramer-whats-going-on-in-there
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- kramer, what's going on in there?
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.335
  y: 0.12
  width: 0.63
  height: 0.2
  align: center
  valign: middle
  color: '#C3B091'
  stroke_width: 0
- name: bottom
  x: 0.03
  y: 0.8
  width: 0.54
  height: 0.2
  align: center
  valign: middle
  color: '#C3B091'
  stroke_width: 0
example_text:
- I put crystals on the router
- packet loss decreased (spiritually)
