name: Probably Not a Good Idea
source: https://www.youtube.com/watch?v=RFinNxS5KN4&t=86
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- probably not a good idea
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- cron job for self-care
- failed with exit code 1
