name: Overly Attached Girlfriend
source: http://knowyourmeme.com/memes/overly-attached-girlfriend
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- overly attached girlfriend
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- I studied the blade
- then the terms of service
