name: Soccer Celebration In A Bar
source: https://knowyourmeme.com/memes/soccer-celebration-in-a-bar
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- english football fans
- wales
- soccer celebration in a bar
background:
  image: default.jpg
text_boxes:
- name: screen
  quad:
  - - 0.14
    - 0.18
  - - 0.54
    - 0.01
  - - 0.55
    - 0.3
  - - 0.15
    - 0.49
  align: center
  valign: middle
  uppercase: true
  color: white
  stroke_width: 2
  max_font_size: 28
example_text:
- push the weird button
