name: What a Country
source: https://www.youtube.com/watch?v=Q8mD2hsxrhQ
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- the simpsons
- dr. nick
- what a country
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- the wifi password is
- an ancient curse
