name: Who Killed Hannibal?
source: https://knowyourmeme.com/memes/who-killed-hannibal
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- who killed hannibal?
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.115
  y: 0.3
  width: 0.27
  height: 0.1
  align: center
  valign: middle
- name: bottom
  x: 0.545
  y: 0.35
  width: 0.27
  height: 0.1
  align: center
  valign: middle
- name: middle
  x: 0.05
  y: 0.875
  width: 0.9
  height: 0.125
  align: center
  valign: middle
  color: '#C3B091'
example_text:
- manifesting abundance
- receiving spam coupons
- mildly prophetic
