name: Mona Lisa
source: https://commons.wikimedia.org/wiki/File:Mona_Lisa.jpg
license: Public domain (Leonardo da Vinci, c. 1503)
keywords:
- smug
- knowing
- smile
- mona lisa
- davinci
- suspicious
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.02
  y: 0.0
  width: 0.96
  height: 0.14
  align: center
  valign: top
  uppercase: true
- name: bottom
  x: 0.02
  y: 0.88
  width: 0.96
  height: 0.1
  align: center
  valign: bottom
  uppercase: true
example_text:
- she's not smiling
- she's buffering
