name: It's A Trap!
source: http://knowyourmeme.com/memes/its-a-trap
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- star wards
- admiral ackbar
- it's a trap!
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- it's a trap
- it's also a bit
