name: Y U NO Guy
source: http://knowyourmeme.com/memes/y-u-no-guy
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- y u no guy
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- Y U NO
- LET ME BE WEIRD
