name: What the Hell is This?
source: https://api.memegen.link/templates/noah
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- family guy noah
- what the hell is this?
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.8
  y: 0.3
  width: 0.18
  height: 0.1
  align: center
  valign: middle
- name: bottom
  x: 0.69
  y: 0.7
  width: 0.18
  height: 0.1
  align: center
  valign: middle
- name: middle
  x: 0.07
  y: 0.68
  width: 0.18
  height: 0.1
  align: center
  valign: middle
- name: line4
  x: 0.05
  y: 0.9
  width: 0.9
  height: 0.1
  align: center
  valign: middle
  color: '#C3B091'
  stroke_width: 0
example_text:
- two of every
- anxiety
- board the ark
- bring snacks
