name: Confession Bear
source: http://knowyourmeme.com/memes/confession-bear
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- confession bear
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- the vibes are rancid
- but the Wi-Fi is free
