name: I Immediately Regret This Decision!
source: https://www.youtube.com/watch?v=gd9ltJGykYc
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- i immediately regret this decision!
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- the prophecy foretold my standup
- it did not mention the crickets
