name: Push it somewhere else Patrick
source: http://knowyourmeme.com/memes/push-it-somewhere-else-patrick
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- push it somewhere else patrick
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.15
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.85
  width: 0.9
  height: 0.15
  align: center
  valign: middle
  uppercase: true
example_text:
- is mayonnaise
- an instrument of chaos?
