name: And It's Gone
source: https://knowyourmeme.com/memes/and-its-gone
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- south park
- and it's gone
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- this inbox zero
- is a temporary hallucination
