name: You Sit on a Throne of Lies
source: http://knowyourmeme.com/memes/you-sit-on-a-throne-of-lies
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- elf
- you sit on a throne of lies
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- cron job for self-care
- failed with exit code 1
