name: The Rent Is Too Damn High
source: http://knowyourmeme.com/memes/the-rent-is-too-damn-high-jimmy-mcmillan
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- the rent is too damn high
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- the stakes are too high
- the bit is higher
