name: Three-Headed Dragon
source: https://knowyourmeme.com/memes/three-headed-dragon
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- king ghidorah
- three-headed dragon
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.0135
  y: 0.65
  width: 0.243
  height: 0.13
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.3785
  y: 0.55
  width: 0.243
  height: 0.13
  align: center
  valign: middle
  uppercase: true
- name: middle
  x: 0.7435
  y: 0.6
  width: 0.243
  height: 0.13
  align: center
  valign: middle
  uppercase: true
example_text:
- me explaining the meme
- to someone who asked for peace
- still processing (emotionally)
