name: Joseph Ducreux
source: https://knowyourmeme.com/memes/joseph-ducreux-archaic-rap
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- archaic rap
- joseph ducreux
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- almost politically correct
- deeply incorrect timing
