name: What Are Ya Gonna Do?
source: https://www.youtube.com/watch?v=76URh0S7YIw
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- what are ya gonna do?
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- what are you guys doing
- on my timeline
