name: At Least You Tried
source: http://knowyourmeme.com/memes/you-tried
license: Imported from jacebrowning/memegen (MIT); see NOTICE.md for template provenance.
keywords:
- at least you tried
background:
  image: default.jpg
text_boxes:
- name: top
  x: 0.05
  y: 0.0
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
- name: bottom
  x: 0.05
  y: 0.8
  width: 0.9
  height: 0.2
  align: center
  valign: middle
  uppercase: true
example_text:
- at least you tried
- to be normal
